// Code generated by protoc-gen-authzen-helpers. DO NOT EDIT.

package authzenv1

import (
	"fmt"

	openfgav1 "github.com/openfga/api/proto/openfga/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/types/known/structpb"
)

// ParseContext extracts typed OpenFGA fields from a context Struct.
// This allows you to access openfga.dev/consistency and openfga.dev/tuples
// as strongly-typed fields while keeping other context values in the Additional map.
//
// Example:
//
//	ctx, err := ParseContext(req.Context)
//	if err != nil {
//	    return err
//	}
//	if ctx.Consistency != nil {
//	    // use typed consistency preference
//	}
func ParseContext(ctx *structpb.Struct) (*ContextData, error) {
	if ctx == nil {
		return &ContextData{
			Additional: make(map[string]*structpb.Value),
		}, nil
	}

	data := &ContextData{
		Additional: make(map[string]*structpb.Value),
	}

	for key, val := range ctx.Fields {
		switch key {
		case "openfga.dev/consistency":
			if strVal, ok := val.Kind.(*structpb.Value_StringValue); ok {
				enumVal, exists := openfgav1.ConsistencyPreference_value[strVal.StringValue]
				if !exists {
					return nil, fmt.Errorf("invalid consistency value: %s", strVal.StringValue)
				}
				consistency := openfgav1.ConsistencyPreference(enumVal)
				data.Consistency = &consistency
			} else {
				return nil, fmt.Errorf("openfga.dev/consistency must be a string")
			}

		case "openfga.dev/tuples":
			jsonData, err := val.MarshalJSON()
			if err != nil {
				return nil, fmt.Errorf("failed to marshal tuples: %w", err)
			}

			var tuples openfgav1.ContextualTupleKeys
			if err := protojson.Unmarshal(jsonData, &tuples); err != nil {
				return nil, fmt.Errorf("failed to parse openfga.dev/tuples: %w", err)
			}
			data.Tuples = &tuples

		default:
			data.Additional[key] = val
		}
	}

	return data, nil
}

// ToStruct converts ContextData back to a google.protobuf.Struct.
// This is useful when constructing requests programmatically.
//
// Example:
//
//	ctx := &ContextData{
//	    Consistency: openfgav1.ConsistencyPreference_HIGHER_CONSISTENCY.Enum(),
//	}
//	structCtx, err := ctx.ToStruct()
//	req := &EvaluationRequest{
//	    Context: structCtx,
//	}
func (c *ContextData) ToStruct() (*structpb.Struct, error) {
	if c == nil {
		return nil, nil
	}

	fields := make(map[string]*structpb.Value)

	if c.Consistency != nil {
		fields["openfga.dev/consistency"] = structpb.NewStringValue(c.Consistency.String())
	}

	if c.Tuples != nil {
		jsonData, err := protojson.Marshal(c.Tuples)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal tuples: %w", err)
		}

		var val structpb.Value
		if err := val.UnmarshalJSON(jsonData); err != nil {
			return nil, fmt.Errorf("failed to create tuples value: %w", err)
		}
		fields["openfga.dev/tuples"] = &val
	}

	for k, v := range c.Additional {
		fields[k] = v
	}

	return &structpb.Struct{Fields: fields}, nil
}
